### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by xiongchiamiov** [alens/Ansible-LikewiseOpen#5]
Section F.1 of [the GitHub terms of service](https://help.github.com/articles/github-terms-of-service/#f-copyright-and-content-ownership) guarantees that people are legally allowed to view this repository, but that's about it; otherwise things fall back to the default copyright status, which usually means that no one is allowed to do anything.

It would be really useful if all the contributors to this project would license their work under a standard open-source license, so the rest of us can actually use it.  If you don't have preferences on licensing, [the MIT license](https://opensource.org/licenses/MIT) is a nice one because of its simplicity, but really anything that's OSI-approved is fine.

**Comment by alens** [comment]
hi!

the licence is  already specified under https://github.com/alens/Ansible-LikewiseOpen/blob/master/meta/main.yml
